# Generated by Django 4.0.3 on 2022-04-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('currentPrice', models.CharField(max_length=20)),
                ('marketCapital', models.CharField(max_length=20)),
                ('graphX', models.CharField(max_length=50, null=True)),
                ('graphY', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('feedback', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtubeLink', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
