# Generated by Django 4.0.3 on 2022-04-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='graphX',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='recommended',
            name='graphY',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
